
version: '3.8'
services:
  luma:
    depends_on:
      - backend
    build:
      context: ./luma
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5173
    # volumes:
    #   - ./luma/package.json:/app/package.json
    #   - ./luma/package-lock.json:/app/package-lock.json
    #   - ./luma/src:/app/src
    # command: sh -c "npm install && npm run dev"
  backend:
    build:
      context:
        ./backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://dhaya123:Dhaya%40123@cluster0.amircbx.mongodb.net/
    # volumes:
    #   - ./backend/package.json:/app/package.json
    #   - ./backend/package-lock.json:/app/package-lock.json
    #   - ./backend:/app
    # command: sh -c "npm install && npm run dev"
    volumes:
      - data:/app

volumes:
  data:
